Feature branch
AkintoyeOlamide/Re-former1 pull request #2
Opened 2020-11-24 16:35 UTC by AkintoyeOlamide

This project is was simply on how forms are created, edited, and submitted with rails.
And this project was made rails version 6.0.3 and ruby version 2.7.1

2020-11-24 16:55 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

A great job so far with this project! 👍 
Just a few adjustments and ready to go 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review ⏩ 
Good luck 😃 

## Mandatory changes
- Commit more often and be more descriptive in your commits, it will help you out to know your trip from the beginning till the end of the project
- Remove all commented out code form your controller

2020-11-24 16:55 UTC, javitocor commented on README.md
> +6. Run `rails db:migrate`.
hen using sqlite you do not need to run db:create, kindly remove it

2020-11-24 16:55 UTC, javitocor commented on app/views/users/new.html.erb
> +  <label for="name">Username:</label>
Modify your action to meet the rails path, ie action="users_path"

2020-11-24 16:55 UTC, javitocor commented on app/views/users/new.html.erb
> +  <%= label_tag 'username', 'Username:'%>
Same here

2020-11-24 16:55 UTC, javitocor commented on app/views/users/new.html.erb
> +  <%= text_field_tag 'email'%>
Use appropriate tag for the email field

2020-11-24 16:55 UTC, javitocor commented on app/views/users/new.html.erb
> +  Password: <%= f.text_field :password, placeholder: '**********' %>
same here, use appropriate field for the email

2020-11-24 16:55 UTC, javitocor commented on app/views/users/edit.html.erb
> +  Password: <%= f.text_field :password, placeholder: '**********' %>
Same here

2020-11-24 17:22 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED 🛑 

A great job with the implemented changes 👍 
But not all of them yet, be sure to implement all the mandatory changes before resubmitting your project
Good luck 😃 

## Mandatory changes
- Kindly make the development branch your default branch
- Your forms form_tag and form_for still does not have the appropriate field for the email, kindly implement it
- Kindly add the 'users_path' to your form_tag form
- In the readme file, kindly modify the db:create by db:migrate in your getting started section
- Modify the email field also in your users/edit.erb

2020-11-25 05:27 UTC, AkintoyeOlamide commented
The new changes that were required by Javier were, were things the previous tse instructed me to do, so it's like the reviews are conflicting with each other.

2020-11-25 05:41 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED 🛑 

Hello Akintoye!
Good job so far! But are some mandatory changes you have to implement that are not yet done!
Let's review them again 💪  apply the changes and request for a new code review ⏩ 

## Mandatory changes
- On your form_tag and in the form_for, in the users new and edit views, apply the following changes. Those changes are necessary in order to apply the appropriate input field for the user, besides all of them comes with extra security features, ie. by default will check if the email provided is valid
    - uses label_tag, text_field_tag, email_field_tag, password_field_tag, for the form_tag
    - `<%= f.email_field :email %>` for the form_for

2020-11-25 08:00 UTC, rOluochKe approved these changes
Hello @AkintoyeOlamide 
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-11-25 08:08 UTC, merged